# minqlxtended - A Quake Live server administrator bot.
# Copyright (C) 2015 Mino <mino@minomino.org>
# Copyright (C) 2024 Thomas Jones <me@thomasjones.id.au>

# This file is part of minqlxtended.

# minqlxtended is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# minqlxtended is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with minqlxtended. If not, see <http://www.gnu.org/licenses/>.

import minqlxtended
import os.path

class docs(minqlxtended.Plugin):
    def __init__(self):
        super().__init__()
        self.add_command("gencmd", self.cmd_gencmd, permission=5, usage="[excluded_plugins]")

    def cmd_gencmd(self, players, msg, channel):
        """Generate a command list based on currently loaded plugins in HTML with Twig filtering."""
        if len(msg) > 1:
            excluded = [s.lower() for s in msg[1:]]
        else:
            excluded = []

        prefix = self.get_cvar("qlx_commandPrefix")
        cmds = {}
        for cmd in minqlxtended.COMMANDS.commands:
            if cmd.plugin.__class__.__name__ in excluded:  # Skip excluded plugins.
                continue

            if cmd.permission not in cmds:
                cmds[cmd.permission] = [cmd]
            else:
                cmds[cmd.permission].append(cmd)

        out = (
            "<h1>Commands</h1>\n"
            "<p>The Purgery's command system is based on permission levels. Players start out with the default permission level "
            "of <strong>0</strong>. A player with level <strong>1</strong> can execute commands for level <strong>1</strong> "
            "and below. A level <strong>2</strong> player can execute level <strong>2</strong>, <strong>1</strong> and "
            "<strong>0</strong> commands, and so on.</p>\n"
        )
        
        for perm in sorted(cmds.keys()):
            if perm:
                out += "{{% if player.permission >= {} %}}\n".format(perm)

            out += "<h2>Permission level <strong>{}</strong>:</h2>\n".format(perm)
            out += "<ul>\n"
            for cmd in sorted(cmds[perm], key=lambda x: x.plugin.__class__.__name__):
                out += "  <li>\n"
                name = prefix + cmd.name[0] if cmd.prefix else cmd.name[0]
                out += "    <code>{}</code>".format(name)
                if len(cmd.name) > 1:  # Aliases?
                    out += " (alternatively "
                    for alias in cmd.name[1:]:
                        name_alias = prefix + alias if cmd.prefix else alias
                        out += "<code>{}</code>, ".format(name_alias)
                    out = out[:-2] + ")"
                out += " from plug-in <em>{}</em>\n".format(cmd.plugin.__class__.__name__)
                
                # Docstring.
                if cmd.handler.__doc__:
                    out += "    <p><pre>{}</pre></p>\n".format(cmd.handler.__doc__)

                # Usage
                if cmd.usage:
                    out += "    <p><em>Usage</em>: <code>{} {}</code></p>\n".format(name, cmd.usage)

                out += "  </li>\n"
            out += "</ul>\n"

            if perm:
                out += "{% endif %}\n"
        
        out += '<em>Automatically generated by <a href="https://github.com/tjone270/minqlxtended">minqlxtended {} (with plug-ins {})</a>.</em>' \
            .format(minqlxtended.__version__, minqlxtended.__plugins_version__)

        with open(os.path.join(self.get_cvar("fs_basepath"), "command_list.twig"), "w") as f:
            f.write(out)

        channel.reply("^7Command list generated!")
